import amirahTemi from '../Assets/Images/amirahTemi.svg'

export type studentsDataType = {
  isActive: boolean
  studentId: string
  studentImage: string
  studentName: string
  emailAddress: string
  fileName: string
  status: string
  grade: string
  enrolledDate: string
  about: string
  country: string
  schoolLevel: string
  linkedinProfile: string
  profileImage: string
  course: string
  displayOptions: boolean
}[]

export const studentsData: studentsDataType = [
  {
    isActive: false,
    studentId: '123456',
    studentImage: amirahTemi,
    studentName: 'Olivia Davis',
    emailAddress: 'olivia.davis@example.com',
    fileName: 'Assignment3.txt',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Future entrepreneur with a passion for business and innovation. Always looking for opportunities to learn and create.',
    country: 'South Africa',
    schoolLevel: 'Postgraduate',
    linkedinProfile: 'https://www.linkedin.com/in/oliviadavis',
    profileImage: 'https://example.com/images/oliviadavis.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '234567',
    studentImage: amirahTemi,
    studentName: 'Daniel Wilson',
    emailAddress: 'daniel.wilson@example.com',
    fileName: 'Assignment3.json',
    status: 'Active',
    grade: '35',
    enrolledDate: '03 Sep, 2022',
    about:
      'Art enthusiast exploring the world of digital art and design. Striving to bring creativity and imagination to life through visual storytelling.',
    country: 'Kenya',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/danielwilson',
    profileImage: 'https://example.com/images/danielwilson.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '345678',
    studentImage: amirahTemi,
    studentName: 'Sophia Moore',
    emailAddress: 'sophia.moore@example.com',
    fileName: 'Assignment3.csv',
    status: 'Active',
    grade: '42',
    enrolledDate: '10 Oct, 2022',
    about:
      'Advocate for social justice and equality. Committed to making a positive impact in the community through activism and awareness.',
    country: 'Nigeria',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/sophiamoore',
    profileImage: 'https://example.com/images/sophiamoore.jpg',
    course: 'Backend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '456789',
    studentImage: amirahTemi,
    studentName: 'Liam Taylor',
    emailAddress: 'liam.taylor@example.com',
    fileName: 'Assignment3.sql',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '18 Nov, 2022',
    about:
      'Sports enthusiast with a love for soccer. Whether playing or watching, the passion for the game is always at the forefront.',
    country: 'Ghana',
    schoolLevel: 'Postgraduate',
    linkedinProfile: 'https://www.linkedin.com/in/liamtaylor',
    profileImage: 'https://example.com/images/liamtaylor.jpg',
    course: 'Backend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '567890',
    studentImage: amirahTemi,
    studentName: 'Ava Jackson',
    emailAddress: 'ava.jackson@example.com',
    fileName: 'Assignment3.xml',
    status: 'Active',
    grade: '38',
    enrolledDate: '25 Dec, 2022',
    about:
      'Science and technology enthusiast. Eager to explore the frontiers of knowledge and contribute to advancements in the field.',
    country: 'South Africa',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/avajackson',
    profileImage: 'https://example.com/images/avajackson.jpg',
    course: 'Backend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '678901',
    studentImage: amirahTemi,
    studentName: 'Sophie Adams',
    emailAddress: 'sophie.adams@example.com',
    fileName: 'Assignment4.docx',
    status: 'Active',
    grade: '29',
    enrolledDate: '15 Jan, 2023',
    about:
      'Tech enthusiast with a focus on artificial intelligence. Constantly exploring ways to apply AI to solve real-world problems.',
    country: 'United Kingdom',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/sophieadams',
    profileImage: 'https://example.com/images/sophieadams.jpg',
    course: 'Backend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '789012',
    studentImage: amirahTemi,
    studentName: 'Ryan Carter',
    emailAddress: 'ryan.carter@example.com',
    fileName: 'Assignment4.pdf',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Feb, 2023',
    about:
      'Passionate about data science and analytics. Aspiring to make data-driven decisions and uncover meaningful insights.',
    country: 'United States',
    schoolLevel: 'Postgraduate',
    linkedinProfile: 'https://www.linkedin.com/in/ryancarter',
    profileImage: 'https://example.com/images/ryancarter.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '890123',
    studentImage: amirahTemi,
    studentName: 'Zara Patel',
    emailAddress: 'zara.patel@example.com',
    fileName: 'Assignment4.pptx',
    status: 'Active',
    grade: '36',
    enrolledDate: '05 Mar, 2023',
    about:
      'Entrepreneurial spirit with a focus on startups and innovation. Dedicated to creating positive change through business ventures.',
    country: 'India',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/zarapatel',
    profileImage: 'https://example.com/images/zarapatel.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '901234',
    studentImage: amirahTemi,
    studentName: 'Lucas Rodriguez',
    emailAddress: 'lucas.rodriguez@example.com',
    fileName: 'Assignment4.csv',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '10 Apr, 2023',
    about:
      'Passionate about sustainable energy and environmental conservation. Striving to make a positive impact on the planet.',
    country: 'Brazil',
    schoolLevel: 'Postgraduate',
    linkedinProfile: 'https://www.linkedin.com/in/lucasrodriguez',
    profileImage: 'https://example.com/images/lucasrodriguez.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '012345',
    studentImage: amirahTemi,
    studentName: 'Mia Kim',
    emailAddress: 'mia.kim@example.com',
    fileName: 'Assignment4.xlsx',
    status: 'Active',
    grade: '42',
    enrolledDate: '25 May, 2023',
    about:
      'Aspiring UX/UI designer with a passion for creating user-centric and visually appealing digital experiences.',
    country: 'South Korea',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/miakim',
    profileImage: 'https://example.com/images/miakim.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '987654',
    studentImage: amirahTemi,
    studentName: 'Elijah Wright',
    emailAddress: 'elijah.wright@example.com',
    fileName: 'Assignment4.doc',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '01 Jun, 2023',
    about:
      'Sports enthusiast and fitness advocate. Believes in maintaining a healthy lifestyle and inspiring others to do the same.',
    country: 'Australia',
    schoolLevel: 'Postgraduate',
    linkedinProfile: 'https://www.linkedin.com/in/elijahwright',
    profileImage: 'https://example.com/images/elijahwright.jpg',
    course: 'Frontend development course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '123321',
    studentImage: amirahTemi,
    studentName: 'Emily Johnson',
    emailAddress: 'emily.johnson@example.com',
    fileName: 'Assignment3.txt',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Passionate about literature and storytelling. Aspiring to become a writer and share captivating stories with the world.',
    country: 'United States',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/emilyjohnson',
    profileImage: 'https://example.com/images/emilyjohnson.jpg',
    course: 'Creative Writing course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '654321',
    studentImage: amirahTemi,
    studentName: 'Mohammed Ali',
    emailAddress: 'mohammed.ali@example.com',
    fileName: 'Assignment3.json',
    status: 'Active',
    grade: '40',
    enrolledDate: '03 Sep, 2022',
    about:
      'Tech enthusiast exploring the world of cybersecurity. Committed to enhancing digital security and privacy for all.',
    country: 'Saudi Arabia',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/mohammedali',
    profileImage: 'https://example.com/images/mohammedali.jpg',
    course: 'Cybersecurity course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '246810',
    studentImage: amirahTemi,
    studentName: 'Maria Garcia',
    emailAddress: 'maria.garcia@example.com',
    fileName: 'Assignment3.csv',
    status: 'Active',
    grade: '35',
    enrolledDate: '10 Oct, 2022',
    about:
      'Passionate about environmental conservation and sustainable living. Striving to make a positive impact on the planet.',
    country: 'Spain',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/mariagarcia',
    profileImage: 'https://example.com/images/mariagarcia.jpg',
    course: 'Environmental Science course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '135791',
    studentImage: amirahTemi,
    studentName: 'Isabella Martinez',
    emailAddress: 'isabella.martinez@example.com',
    fileName: 'Assignment3.txt',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Passionate about mathematics and problem-solving. Aspiring to pursue a career in data science and analytics.',
    country: 'Mexico',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/isabellamartinez',
    profileImage: 'https://example.com/images/isabellamartinez.jpg',
    course: 'Data Science course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '24681012',
    studentImage: amirahTemi,
    studentName: 'Alexander Thompson',
    emailAddress: 'alexander.thompson@example.com',
    fileName: 'Assignment3.json',
    status: 'Active',
    grade: '38',
    enrolledDate: '03 Sep, 2022',
    about:
      'Avid traveler and cultural enthusiast. Passionate about exploring new destinations and experiencing diverse cultures.',
    country: 'Canada',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/alexanderthompson',
    profileImage: 'https://example.com/images/alexanderthompson.jpg',
    course: 'Cultural Studies course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '11223344',
    studentImage: amirahTemi,
    studentName: 'Luna Hernandez',
    emailAddress: 'luna.hernandez@example.com',
    fileName: 'Assignment3.csv',
    status: 'Active',
    grade: '45',
    enrolledDate: '10 Oct, 2022',
    about:
      'Passionate about music and performance arts. Dedicated to expressing emotions and stories through the art of music.',
    country: 'Argentina',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/lunahernandez',
    profileImage: 'https://example.com/images/lunahernandez.jpg',
    course: 'Music Theory course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '151617',
    studentImage: amirahTemi,
    studentName: 'Emma White',
    emailAddress: 'emma.white@example.com',
    fileName: 'Assignment3.txt',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Passionate about astronomy and space exploration. Aspiring to contribute to the exploration of the universe.',
    country: 'United States',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/emmawhite',
    profileImage: 'https://example.com/images/emmawhite.jpg',
    course: 'Astrophysics course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '181920',
    studentImage: amirahTemi,
    studentName: 'Nathan Lee',
    emailAddress: 'nathan.lee@example.com',
    fileName: 'Assignment3.json',
    status: 'Active',
    grade: '40',
    enrolledDate: '03 Sep, 2022',
    about:
      'Passionate about computer science and software development. Aspiring to create innovative software solutions.',
    country: 'Canada',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/nathanlee',
    profileImage: 'https://example.com/images/nathanlee.jpg',
    course: 'Software Engineering course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '212223',
    studentImage: amirahTemi,
    studentName: 'Sophia Brown',
    emailAddress: 'sophia.brown@example.com',
    fileName: 'Assignment3.csv',
    status: 'Active',
    grade: '45',
    enrolledDate: '10 Oct, 2022',
    about:
      'Passionate about environmental conservation and sustainable living. Striving to make a positive impact on the planet.',
    country: 'Australia',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/sophiabrown',
    profileImage: 'https://example.com/images/sophiabrown.jpg',
    course: 'Environmental Studies course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '242526',
    studentImage: amirahTemi,
    studentName: 'Jacob Wright',
    emailAddress: 'jacob.wright@example.com',
    fileName: 'Assignment3.xml',
    status: 'Active',
    grade: '42',
    enrolledDate: '25 Dec, 2022',
    about:
      'Passionate about literature and storytelling. Aspiring to become a successful novelist and share captivating stories.',
    country: 'United Kingdom',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/jacobwright',
    profileImage: 'https://example.com/images/jacobwright.jpg',
    course: 'Creative Writing course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '272829',
    studentImage: amirahTemi,
    studentName: 'Elena Rodriguez',
    emailAddress: 'elena.rodriguez@example.com',
    fileName: 'Assignment3.docx',
    status: 'Active',
    grade: '38',
    enrolledDate: '15 Jan, 2023',
    about:
      'Passionate about psychology and human behavior. Striving to understand the complexities of the human mind.',
    country: 'Spain',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/elenarodriguez',
    profileImage: 'https://example.com/images/elenarodriguez.jpg',
    course: 'Psychology course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '303132',
    studentImage: amirahTemi,
    studentName: 'David Kim',
    emailAddress: 'david.kim@example.com',
    fileName: 'Assignment3.pdf',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Passionate about graphic design and visual communication. Aspiring to create impactful designs that resonate with audiences.',
    country: 'South Korea',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/davidkim',
    profileImage: 'https://example.com/images/davidkim.jpg',
    course: 'Graphic Design course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '333435',
    studentImage: amirahTemi,
    studentName: 'Anna Nguyen',
    emailAddress: 'anna.nguyen@example.com',
    fileName: 'Assignment3.pptx',
    status: 'Active',
    grade: '40',
    enrolledDate: '03 Sep, 2022',
    about:
      'Passionate about public health and community well-being. Committed to improving access to healthcare services for all.',
    country: 'Vietnam',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/annanguyen',
    profileImage: 'https://example.com/images/annanguyen.jpg',
    course: 'Public Health course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '363738',
    studentImage: amirahTemi,
    studentName: 'Michael Chen',
    emailAddress: 'michael.chen@example.com',
    fileName: 'Assignment3.doc',
    status: 'Active',
    grade: '45',
    enrolledDate: '10 Oct, 2022',
    about:
      'Passionate about entrepreneurship and business development. Aspiring to launch innovative startups that solve real-world problems.',
    country: 'China',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/michaelchen',
    profileImage: 'https://example.com/images/michaelchen.jpg',
    course: 'Entrepreneurship course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '394041',
    studentImage: amirahTemi,
    studentName: 'Sarah Smith',
    emailAddress: 'sarah.smith@example.com',
    fileName: 'Assignment3.xlsx',
    status: 'Active',
    grade: '42',
    enrolledDate: '25 Dec, 2022',
    about:
      'Passionate about environmental conservation and sustainability. Committed to raising awareness and implementing eco-friendly practices.',
    country: 'United States',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/sarahsmith',
    profileImage: 'https://example.com/images/sarahsmith.jpg',
    course: 'Environmental Sustainability course',
    displayOptions: false,
  },
  {
    isActive: false,
    studentId: '424344',
    studentImage: amirahTemi,
    studentName: 'Thomas Wilson',
    emailAddress: 'thomas.wilson@example.com',
    fileName: 'Assignment3.txt',
    status: 'Inactive',
    grade: 'Not graded',
    enrolledDate: '20 Aug, 2022',
    about:
      'Passionate about artificial intelligence and machine learning. Aspiring to develop AI-powered solutions for various industries.',
    country: 'United Kingdom',
    schoolLevel: 'Undergraduate',
    linkedinProfile: 'https://www.linkedin.com/in/thomaswilson',
    profileImage: 'https://example.com/images/thomaswilson.jpg',
    course: 'Artificial Intelligence course',
    displayOptions: false,
  },
];
